version: '3.7'

services:

  code-tutor-ui:
    container_name: code-tutor-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:4200'